// <auto-generated />
namespace TollywoodMDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MovieVideosTableMigandMoviesChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieVideosTableMigandMoviesChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201704271151569_MovieVideosTableMigandMoviesChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
