// <auto-generated />
namespace TollywoodMDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class datimechangeforReviewsTablemig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datimechangeforReviewsTablemig));
        
        string IMigrationMetadata.Id
        {
            get { return "201704160708579_datimechangeforReviewsTablemig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
