// <auto-generated />
namespace TollywoodMDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addMovie_Release_Dateproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMovie_Release_Dateproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201703231324298_addMovie_Release_Dateproperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
